# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TaCyhG0pJIMRzOWlcEeVkQ3LOdG1dd0C
"""

!pip install streamlit

# Import required libraries
import streamlit as st

# Title of the app
st.title('Class Feedback App')

# Create text inputs for the user's name, university, class, and thoughts
name = st.text_input('Enter your name:')
university = st.text_input('Enter your university:')
class_name = st.text_input('Enter your class:')
thoughts = st.text_area('Share your thoughts on how this class is being run:')

# Display the user's input
if st.button('Submit Feedback'):
    st.write(f"Thank you, {name}!")
    st.write(f"University: {university}")
    st.write(f"Class: {class_name}")
    st.write("Your thoughts:")
    st.write(thoughts)